services:
  redis:
    image: redis:7.0.7
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 120
    networks:
      - ugc

  mongodb:
    image: mongo
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 2s
      timeout: 5s
      retries: 120
    networks:
      - ugc

  api:
    build: ./ugs_api
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
      - JWT_VALIDATE=0
    expose:
      - 8000
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: ugs_api
    networks:
      - ugc

  nginx:
    image: nginx:1.23.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - api
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: nginx
    networks:
      - ugc

networks:
   ugc:
     name: ugc