version: '3'
services:
  elastic:
    image: elasticsearch:7.17.9
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - ugc

  kibana:
    image: kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=["http://elastic:9200"]
    ports:
      - 5601:5601
    depends_on:
      - elastic
    networks:
      - ugc

  logstash:
    image: logstash:7.17.9
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=["http://elastic:9200"]
      - ES_HOST=http://elastic:9200
    ports:
      - 5044:5044/udp
      - 5045:5045
    volumes:
      - ./logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    depends_on:
      - elastic
    networks:
      - ugc

volumes:
  elastic_data:

networks:
   ugc:
     name: ugc