name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{matrix.version}}
        uses: actions/setup-python@v3.1.3
        with:
          python-version: ${{matrix.version}}
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          
      - name: Lint with flake8
        run: |
          flake8 . --config=flake8.cfg --count --show-source

      - name: Mypy Check
        uses: jpetrucciani/mypy-check@0.991
        with:
          mypy_flags: --ignore-missing-imports
          python_version: ${{matrix.version}}

      - name: Send telegram message on pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created pull request: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}, Python ${{matrix.version}}, Workflow: ${{ github.workflow }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
